language: python

python:
  - "3.8"

install:
  - pip3 install paho-mqtt

services:
  - docker

script:
  - mkdir output && chmod -R 777 output
  - export USERID=$(id -u $(whoami)) && export GROUP=$(id -g $(whoami)) && docker-compose up --build
  - ls -la ./output
  - rm ./output/config-template.ini
  - mv config.ini ./output/config.ini
  - cd output && python3 main.py & && sleep 15 && exit 0