language: python

services:
  - docker

script:
  - docker-compose up --build
  - ls -la ./output
  - rm ./output/config-template.ini
  - mv config.ini ./output/config.ini
  - cd output && python3 main.py