asyncapi-to-python:
  build: ./
  container_name: asyncapi-to-python
  environment:
    - NODE_ENV=production
  command: ["${APIYAML}"]
  volumes:
    - ${APIPATH}:/tmp/python-paho-template/api
    - ${CODEPATH}:/tmp/python-paho-template/code
